SELECT SMS_R_SYSTEM.ResourceID,SMS_R_SYSTEM.ResourceType,SMS_R_SYSTEM.Name,SMS_R_SYSTEM.SMSUniqueIdentifier,SMS_R_SYSTEM.ResourceDomainORWorkgroup,SMS_R_SYSTEM.Client 
FROM SMS_R_System 
INNER JOIN SMS_G_System_SOFTWARE_LICENSING_PRODUCT 
ON SMS_G_System_SOFTWARE_LICENSING_PRODUCT.ResourceID = SMS_R_System.ResourceId 
WHERE SMS_G_System_SOFTWARE_LICENSING_PRODUCT.ApplicationID = "55c92734-d682-4d71-983e-d6ec3f16059f" 
AND (SMS_G_System_SOFTWARE_LICENSING_PRODUCT.LicenseStatus != 0 AND SMS_G_System_SOFTWARE_LICENSING_PRODUCT.LicenseStatus != 1)
